### ISSUE TITLE
org.bukkit.event.EventException: null

### ISSUE THREAD

**Issue by HimaJyun** [HimaJyun/ChestSafe#9]
Spigot 1.14.1

```
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:320) ~[minecraft_server.jar:git-Spigot-8043ebc-89c52b7]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[minecraft_server.jar:git-Spigot-8043ebc-89c52b7]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:520) [minecraft_server.jar:git-Spigot-8043ebc-89c52b7]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:505) [minecraft_server.jar:git-Spigot-8043ebc-89c52b7]
	at net.minecraft.server.v1_14_R1.TileEntityHopper.u(TileEntityHopper.java:220) [minecraft_server.jar:git-Spigot-8043ebc-89c52b7]
	at net.minecraft.server.v1_14_R1.TileEntityHopper.a(TileEntityHopper.java:135) [minecraft_server.jar:git-Spigot-8043ebc-89c52b7]
	at net.minecraft.server.v1_14_R1.TileEntityHopper.tick(TileEntityHopper.java:117) [minecraft_server.jar:git-Spigot-8043ebc-89c52b7]
	at net.minecraft.server.v1_14_R1.World.tickBlockEntities(World.java:670) [minecraft_server.jar:git-Spigot-8043ebc-89c52b7]
	at net.minecraft.server.v1_14_R1.WorldServer.doTick(WorldServer.java:369) [minecraft_server.jar:git-Spigot-8043ebc-89c52b7]
	at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1057) [minecraft_server.jar:git-Spigot-8043ebc-89c52b7]
	at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:396) [minecraft_server.jar:git-Spigot-8043ebc-89c52b7]
	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:956) [minecraft_server.jar:git-Spigot-8043ebc-89c52b7]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:801) [minecraft_server.jar:git-Spigot-8043ebc-89c52b7]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.NullPointerException
	at jp.jyn.chestsafe.listener.BlockListener.onInventoryMoveItem(BlockListener.java:80) ~[?:?]
	at jdk.internal.reflect.GeneratedMethodAccessor15.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316) ~[minecraft_server.jar:git-Spigot-8043ebc-89c52b7]
	... 13 more
```

**Comment by HimaJyun** [comment]
コンポスターにホッパーでアイテムを入れるときに発生

**Comment by HimaJyun** [comment]
`block.getLocation()`がコンポスター相手だとnullになる、Spigotのバグか？
